events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Slahses hata diye gaye hain taake redirect na ho
        location /api/v1/auth {
            proxy_pass http://host.docker.internal:3001/api/v1/auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/v1/users {
            proxy_pass http://host.docker.internal:3001/api/v1/users;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/v1/products {
            proxy_pass http://host.docker.internal:3002/api/v1/products;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/v1/orders {
            proxy_pass http://host.docker.internal:3003/api/v1/orders;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}