version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_MULTIPLE_DATABASES: ecommerce_orders,ecommerce_products,ecommerce_users
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-databases.sh

  mongodb:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: secret

  # 👇👇👇 YEH NAYA HISSA ADD KIYA HAI 👇👇👇
  api-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"   # Hum NGINX ko port 8080 par access karenge
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - mongodb
      - redis
      - rabbitmq

volumes:
  postgres_data:
  mongo_data: